function data = JAHimportExcel(workbookFile, sheetName, range)
% workbookFile='C:\Users\James\Documents\Dropbox\Lab\mfiles\vitro\20150619 ANAL DATA.xlsx';
% sheetName=1;
% range='d4:d200';
% 
% 
% 
%IMPORTFILE Import data from a spreadsheet
%   DATA = IMPORTFILE(FILE) reads data from the first worksheet in the
%   Microsoft Excel spreadsheet file named FILE and returns the data as a
%   cell array.
%
%   DATA = IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   DATA = IMPORTFILE(FILE,SHEET,RANGE) reads from the specified worksheet
%   and from the specified RANGE. Specify RANGE using the syntax
%   'C1:C2',where C1 and C2 are opposing corners of the region.%
% Example:
%   ANALDATA = importfile('20150619 ANAL DATA.xlsx','Data','D1:D112');
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2015/06/24 10:57:04
%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If no range is specified, read all data
if nargin <= 2 || isempty(range)
    range = '';
end

%% Import the data
[~, ~, data] = xlsread(workbookFile, sheetName, range);
data(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),data)) = {''};
%% Exclude rows with blank cells
I = any(cellfun(@(x) isempty(x) || (ischar(x) && all(x==' ')),data),2); % Find row with blank cells
data(I,:) = [];